# Gradle
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
# 本机 JDK 20（勿用 Android Studio 的 JBR 25）
org.gradle.java.home=E:/JAVA/20
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

# Kotlin
kotlin.code.style=official
