"""Subset the product's own typeface (HarmonyOS Sans SC, shipped in the app at app/src/main/res/font/)
to this film's characters → fonts/*.woff2 + anchor-fonts.js (inlined, one file, loadable over file://).

The film is set in the app's own face, so the product and the film cannot disagree about the type.
Deterministic: same text in → same bytes out. Re-run after the copy changes (every new string in comp.html
must be in the subset, or a missing glyph shows as a fallback face).

    PYTHONUTF8=1 py tools/mkfonts.py
"""
import base64, json, pathlib, sys
from fontTools import subset

ROOT = pathlib.Path(__file__).resolve().parent.parent           # E:\Anchor\film
APP_FONT = pathlib.Path("E:/Anchor/app/src/main/res/font")
WEIGHTS = {400: "harmonyos_sans_sc_regular.ttf",                # AnchorType Regular
           600: "harmonyos_sans_sc_medium.ttf",                 # Compose declares medium as W600
           700: "harmonyos_sans_sc_bold.ttf"}                   # AnchorType Bold
# every file whose literal text can reach the screen
TEXT_SRC = ["comp.html", "anchor-fonts.js", "vo/lines.txt", "vo/zh-CN-YunyangNeural/subs.json"]
# ASCII (the replica shows digits) + the punctuation the app's Chinese uses
EXTRA = "".join(chr(c) for c in range(0x20, 0x7F)) + "·—–…‘’“”，。、：；？！（）【】《》％%°±→←↑↓"


def main() -> int:
    chars = set(EXTRA)
    for rel in TEXT_SRC:
        p = ROOT / rel
        if p.exists():
            chars |= set(p.read_text(encoding="utf-8", errors="ignore"))
    chars = "".join(sorted(chars))
    (ROOT / "fonts" / "_chars.txt").write_text(chars, encoding="utf-8")

    faces, total = [], 0
    for w, fn in WEIGHTS.items():
        src = APP_FONT / fn
        if not src.exists():
            print(f"missing {src}", file=sys.stderr)
            return 1
        out = ROOT / "fonts" / f"anchor-{w}.woff2"
        subset.main([str(src), f"--text-file={ROOT/'fonts'/'_chars.txt'}",
                     "--flavor=woff2", "--with-zopfli" if False else "--layout-features=kern,liga,tnum",
                     "--no-hinting", "--desubroutinize", f"--output-file={out}"])
        b = out.read_bytes()
        total += len(b)
        faces.append("@font-face{font-family:'Anchor';font-style:normal;font-weight:%d;font-display:block;"
                     "src:url(data:font/woff2;base64,%s) format('woff2')}" % (w, base64.b64encode(b).decode()))
        print(f"anchor-{w}.woff2  {len(b)/1024:6.1f} KB   glyphs={len(chars)}")

    js = ("/* generated by tools/mkfonts.py — do not edit.\n"
          "   HarmonyOS Sans SC, the app's own face (app/src/main/res/font/), subset to this film's text and\n"
          "   inlined so the composition is a single file over file://. © Huawei, free for commercial use. */\n"
          "window.ANCHOR=(function(){\n"
          "  var s=document.createElement('style');s.textContent=" + json.dumps("\n".join(faces)) + ";document.head.appendChild(s);\n"
          "  var load=function(w){return document.fonts.load(w+' 64px Anchor').catch(function(){return null})};\n"
          "  return {ready:Promise.all([load(400),load(600),load(700)]).then(function(){return document.fonts.ready}),"
          "family:'Anchor'};\n"
          "})();\n")
    (ROOT / "anchor-fonts.js").write_text(js, encoding="utf-8")
    print(f"anchor-fonts.js   {len(js)/1024:6.1f} KB  (woff2 total {total/1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
