#!/usr/bin/env python
"""vo/<voice>/plan.json + subs.json -> subs.js

plan.json already carries `lead`, so every timestamp in it is already on the FILM's clock:
no offset is applied here. Emits
  window.VO   = { voice, total, lead, lines:[{i,text,start,end}], subs:[[t0,t1,text], ...] }
  window.SUBS = [[t0,t1,text], ...]   <- what gets burned into the picture (one entry per spoken line,
                                         segments are too jumpy to read as subtitles)
  window.DUR  = total + tail
Run: py tools/mksubs.py [voice]
"""
import json
import pathlib
import sys

TAIL = 1.6  # silence after the last word, before the last frame

root = pathlib.Path(__file__).resolve().parent.parent
voice = sys.argv[1] if len(sys.argv) > 1 else "zh-CN-YunyangNeural"
d = root / "vo" / voice
plan = json.loads((d / "plan.json").read_text(encoding="utf-8"))
segs = json.loads((d / "subs.json").read_text(encoding="utf-8"))

lines = [
    {"i": l["i"], "text": l["text"], "start": round(l["start"], 3), "end": round(l["end"], 3)}
    for l in plan["lines"]
]
subs = [[round(a, 3), round(b, 3), t] for a, b, t in segs]
burn = [[l["start"], l["end"], l["text"].rstrip("，。、")] for l in lines]
dur = round(max(l["end"] for l in lines) + TAIL, 2)

body = (
    "// generated by tools/mksubs.py from vo/%s/plan.json + subs.json — do not edit by hand\n"
    "window.VO = %s;\n"
    "window.SUBS = %s;\n"
    "window.DUR = %s;\n"
) % (
    voice,
    json.dumps(
        {"voice": voice, "total": plan["total"], "lead": plan["lead"], "lines": lines, "subs": subs},
        ensure_ascii=False,
        indent=0,
    ),
    json.dumps(burn, ensure_ascii=False),
    dur,
)
(root / "subs.js").write_text(body, encoding="utf-8")
print("subs.js: %d lines, %d segments, dur %.2fs (last word %.2f)" % (len(lines), len(subs), dur, dur - TAIL))
for l in lines:
    print("  %6.3f–%6.3f  %s" % (l["start"], l["end"], l["text"]))
